name: Deploy Site
on:
  push:
    paths:
      - "src/**"
      - "public/**"

jobs:
  Deploy:
    name: AWS Deploy website 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Download Dependencies
        run: npm install

      - name: Build
        run: npm run build
        env: 
          CI: false

      - name: Init new repo in dist folder and commit generated files
        run: |
          cd ./build
          git init
          git add -A
          git config --local user.email "abubukker.chaudhary@gmail.com"
          git config --local user.name "LunarFang416"
          git commit -m 'deploy'

      - name: Force push to destination branch
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: ./build

      - name: Sync with AWS S3
        run: aws s3 cp build s3://${{ secrets.S3_BUCKET }} --recursive

      - name: CloudFront Invalidation
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"